# Brief details about List in Python

List is a data type in python, which can holds multiple values in a single variable. 
List can stores multiple values of different data type into that variable

In [1]:
list = [1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


# Introduction to Numpy

Numpy is a package in python which are used to manipulate numpy arrays in python. 

In [3]:
import numpy as np

# Numpy Array

Numpy array can holds multiple values of same data type
Numpy array method declaration: 
    array(arg1: list or integer type [required], arg2: ndmin [optional])
    
If a list contains values of different data types then it automatically convert all elements into string data type and store into the array.

## 1 Dimension Array Initialization

In [4]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [5]:
list = [1, "Hello", 2, 4, "World"]
arr = np.array(list)
print(list)
print(arr)

[1, 'Hello', 2, 4, 'World']
['1' 'Hello' '2' '4' 'World']


## 2 Dimension Array Initialization

In [6]:
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In 2 dimension array, if the number of elements are not equal in different rows, then python interpreter raise a warning and print the array into one dimension with the list.

In [7]:
arr3 = np.array([[1,2,3,4], [5,6,7]])
print(arr3)
print(arr3.ndim)

[list([1, 2, 3, 4]) list([5, 6, 7])]
1


C:\Users\nirja\AppData\Local\Temp\ipykernel_18300\3418247744.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[1,2,3,4], [5,6,7]])


## 3 Dimension Array Initialization

In [8]:
arr4 = np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[1,2,3,4]]])
print(arr4)
print(arr4.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[5 6 7 8]
  [1 2 3 4]]]
3


## Multi Dimentional Array Initialization

In [9]:
# 5 Dimenstional Array
print("5 Dimentional Array: ")
arr5 = np.array([1,2,3,4], ndmin=5)
print(arr5)
print(arr5.ndim)

print("\n 10 Dimentional Array: ")
#10 dimension array:
arr6 = np.array(['a', 'b', 'c', 'd'], ndmin=10)
print(arr6)
print(arr6.ndim)

5 Dimentional Array: 
[[[[[1 2 3 4]]]]]
5

 10 Dimentional Array: 
[[[[[[[[[['a' 'b' 'c' 'd']]]]]]]]]]
10


## 0 Dimentional Array

arr7 is a 0 dimension array with the value of 42

In [10]:
arr7 = np.array(42)
print(arr7)
print(arr7.ndim)

42
0


# Summary:

In [11]:
print("\n 0 Dimension Array: ", arr7)
print("\n 1 Dimension Array: ", arr)
print("\n 2 Dimension Array: ", arr2)
print("\n 3 Dimension Array: ", arr4)
print("\n 5 Dimension Array: ", arr5)
print("\n 10 Dimension Array: ", arr6)


 0 Dimension Array:  42

 1 Dimension Array:  ['1' 'Hello' '2' '4' 'World']

 2 Dimension Array:  [[1 2 3 4]
 [5 6 7 8]]

 3 Dimension Array:  [[[1 2 3 4]
  [5 6 7 8]]

 [[5 6 7 8]
  [1 2 3 4]]]

 5 Dimension Array:  [[[[[1 2 3 4]]]]]

 10 Dimension Array:  [[[[[[[[[['a' 'b' 'c' 'd']]]]]]]]]]
