# Zeors Array

In [3]:
import numpy as np

#Zeors array of 1 dimention
arr = np.zeros(4)
print(arr)

print()
#Zeors array of 2 dimention
arr = np.zeros((3,4))
print(arr)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones Array

In [5]:
#Ones array of 1 dimention
arr1 = np.ones(4)
print(arr1)

print()
#Ones array of 2 dimention
arr1 = np.ones((3,4))
print(arr1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty Array

Empty array is an array in python which consists either a null value or no element

In [7]:
arr2 = np.empty(5)
print(arr2)
print()
arr2 = np.empty((3,5))
print(arr2)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.41243347e-311
 0.00000000e+000]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Range Array

Range array is an another type of array in python, which stores values in array starting from 0 (by default) and increments by 1 (by default) and stops before a specified number. We use arange function to create a range array.

arange Function Declaration:
       arange(arg1: Start Value [Optional](by Default:0), arg2: End Value[Required], arg3: Step Size [Optional](by Default:1))

In [13]:
arr3 = np.arange(5)
print(arr3)
print()

arr3 = np.arange(3,9)
print(arr3)
print()

arr3 = np.arange(1,10,2)
print(arr3)

[0 1 2 3 4]

[3 4 5 6 7 8]

[1 3 5 7 9]


# Diagonal Array

Diagonal Array is similar to Identity Matrix, whereas the all diagonal elements are 1. We use eye function to create a diagonal array.

eye Function Declaration:
    

In [15]:
#Square Matrix
arr4 = np.eye(3)
print(arr4)
print()

#Rectangular Matrix
arr4 = np.eye(3,5)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace Method

linspace method Declaration:
    linspace(arg1: Start Value[Required], arg2: End Value[Required], arg3: length of Array[Optional](by Default: 50))

In [20]:
arr5 = np.linspace(0, 100)
print(arr5)
print()

arr5 = np.linspace(1, 10,5)
print(arr5)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]

[ 1.    3.25  5.5   7.75 10.  ]
