# Array Indexing

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number.

## 1D Array

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
#               0  1  2  3   <- Positive Indexing
#              -4 -3 -2 -1   <- Negative Indexing
print(arr1)
print(arr1[0])
print(arr1[-2])
print(arr1[5])

[1 2 3 4]
1
3


IndexError: index 5 is out of bounds for axis 0 with size 4

## 2D Array

In [8]:
arr2 = np.array([ [1,2,3,4], [3,4,5,6] ])
print(arr2)
print()

print(arr2[1])
print(arr2[0][3]) #4
print(arr2[0, 3]) #4
print(arr2[1, 0]) #3
print(arr2[5, 0]) #Error

[[1 2 3 4]
 [3 4 5 6]]

[3 4 5 6]
4
4
3


IndexError: index 5 is out of bounds for axis 0 with size 2

## 3D Array

In [9]:
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3)

print()
print(arr3[0])

print()
print(arr3[0,1])

print()
print(arr3[0,1,1]) #5
print(arr3[1,0,2]) #9

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[1 2 3]
 [4 5 6]]

[4 5 6]

5
9


# Array Slicing

Slicing in python means taking elements from one given index to another given index.

## 1D Array

In [10]:
arr1 = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
#                 0    1    2    3    4    5    6
print(arr1)
print()

['A' 'B' 'C' 'D' 'E' 'F' 'G']



For slicing we use 3 arguments, which are separated by collon(:) -> 
arg1: start index[Optional](by default=0), arg2: end index[Optional](by default=len(array)), arg3: step size[Optional](by default=1)

### Positive Slicing

In [11]:
print("'B' to 'E': ",arr1[1:5])

print()
print("'B' to End : ", arr1[1:])

print()
print("Start to 'F': ", arr1[:6])

print()
print(arr1[:])

print()
print(arr1[::2])

print()
print(arr1[1:6:2])

'B' to 'E':  ['B' 'C' 'D' 'E']

'B' to End :  ['B' 'C' 'D' 'E' 'F' 'G']

Start to 'F':  ['A' 'B' 'C' 'D' 'E' 'F']

['A' 'B' 'C' 'D' 'E' 'F' 'G']

['A' 'C' 'E' 'G']

['B' 'D' 'F']


### Negative Slicing

In [12]:
print("'B' to 'E': ",arr1[-6:-2])

print()
print("'B' to End : ", arr1[-6:])

print()
print("Start to 'F': ", arr1[:-1])

print()
print(arr1[-1:-7])  #Invalid Operation

print()
print(arr1[-6:-1:2])

'B' to 'E':  ['B' 'C' 'D' 'E']

'B' to End :  ['B' 'C' 'D' 'E' 'F' 'G']

Start to 'F':  ['A' 'B' 'C' 'D' 'E' 'F']

[]

['B' 'D' 'F']


## 2D Array

In [13]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

print()
print(arr2[1,1:])

print()
print(arr2[:1,4])

print()
print(arr2[0:2,2])

print()
print(arr2[0,1:1,4])   #Error

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 7  8  9 10]

[5]

[3 8]



IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed