# Datatypes in NumPy

Numpy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
Below is a list of all data types in NumPy and the characters used to represent them.

> b - boolean                                           
> i - integer                                
> u - unsigned integer                         
> f - float                                   
> c - complex float                               
> m - timedelta                                   
> M - datetime                                  
> O - object                                    
> S - string                                            
> U - unicode string                                          
> V - fixed chunk of memory for other type ( void )


For i, u, f, S and U we can define size as well.

dtype   :               variants                 
--------------------------------------------------
> int      : int8, int16, int32, int64           
> uint     : uint8, uint16, uint32, uint64         
> bool     : bool                                 
> float    : float16, float32, float64, float128                        
> complex  : complex64, complex128, complex256   

## Checking the datatype of an array

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print("Datatype: ", arr.dtype)

[1 2 3 4 5]
Datatype:  int32


In [4]:
arr = np.array([1+2j, 2+6j, 9-0j])
print(arr)
print("Datatype: ", arr.dtype)

[1.+2.j 2.+6.j 9.+0.j]
Datatype:  complex128


In [28]:
arr = np.array(["Hello", "World", "Good", "Day"])
print(arr)
print("Datatype: ", arr.dtype)

['Hello' 'World' 'Good' 'Day']
Datatype:  <U5


In [29]:
arr = np.array(["Hello", "World", "Good", "Day", 1, 2,3])
print(arr)
print("Datatype: ", arr.dtype)

['Hello' 'World' 'Good' 'Day' '1' '2' '3']
Datatype:  <U11


In [30]:
arr = np.array(["Hello", "World", "Good", "Day", 1.36, 2.56])
print(arr)
print("Datatype: ", arr.dtype)

['Hello' 'World' 'Good' 'Day' '1.36' '2.56']
Datatype:  <U32


In [31]:
arr = np.array(["Hello", "World", "Good", "Day", 1+6i, 2-9i])
print(arr)
print("Datatype: ", arr.dtype)

SyntaxError: invalid syntax (184257450.py, line 1)

## Change datatype of an array

In [10]:
arr = np.array([1,2,3,4,5], dtype = np.int8)
print(arr)
print("Datatype: ", arr.dtype)

[1 2 3 4 5]
Datatype:  int8


In [11]:
arr = np.array([1,2,3,4,5], dtype = "f")
print(arr)
print("Datatype: ", arr.dtype)

[1. 2. 3. 4. 5.]
Datatype:  float32


In [16]:
arr = np.array([-1,-2,-3,4,5], dtype = "u1")
print(arr)
print("Datatype: ", arr.dtype)

[255 254 253   4   5]
Datatype:  uint8


In [17]:
arr = np.array([-1,-2,-3,4,5], dtype = "u2")
print(arr)
print("Datatype: ", arr.dtype)

[65535 65534 65533     4     5]
Datatype:  uint16


In [20]:
arr = np.array([-1,-2,-3,4,5, "Hello"], dtype = "U7")
print(arr)
print("Datatype: ", arr.dtype)

['-1' '-2' '-3' '4' '5' 'Hello']
Datatype:  <U7


## Changing Datatype of an array using function

In [25]:
arr = np.array([1,2,3,4,5])
arr1 = arr.astype(float)
print(arr)
print("Datatype: ", arr.dtype)
print(arr1)
print("Datatype: ", arr1.dtype)

[1 2 3 4 5]
Datatype:  int32
[1. 2. 3. 4. 5.]
Datatype:  float64


In [34]:
arr = np.array([1,2,3,4,5])
arr1 = arr.astype(object)
print(arr)
print("Datatype: ", arr.dtype)
print(arr1)
print("Datatype: ", arr1.dtype)

[1 2 3 4 5]
Datatype:  int32
[1 2 3 4 5]
Datatype:  object


In [26]:
arr = np.array([1,2,3,4,5])
arr1 = np.float32(arr)
print(arr)
print("Datatype: ", arr.dtype)
print(arr1)
print("Datatype: ", arr1.dtype)

[1 2 3 4 5]
Datatype:  int32
[1. 2. 3. 4. 5.]
Datatype:  float32


In [36]:
arr = np.array([-1,-2,3,4,5])
arr1 = np.uint16(arr)
print(arr)
print("Datatype: ", arr.dtype)
print(arr1)
print("Datatype: ", arr1.dtype)

[-1 -2  3  4  5]
Datatype:  int32
[65535 65534     3     4     5]
Datatype:  uint16


In [38]:
arr = np.array([1,2,3,4,5,"hello"])
print(arr)
print("Datatype: ", arr.dtype)

arr1 = np.int32(arr)
print(arr1)
print("Datatype: ", arr1.dtype)

['1' '2' '3' '4' '5' 'hello']
Datatype:  <U11


ValueError: invalid literal for int() with base 10: 'hello'

If a type is given in which elements can not be casted then NumPy will raise a ValueError.                         
ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In the last example, the datatype of the array is UNICODE STRING. In that array, the last element is string type which can't converted into integer datatype due to loss of data. That's why NumPy raise ValueError.