# Arithmetic Operations on NumPy

NumPy provides a wide range of operations that can perform on arrays, including arithmetic operations. NumPy's arithmetic operations are widely used due to their ability to perform simple and efficient calculations on arrays.


Here's a list of various arithmetic operations along with their associated operators and built-in functions:

Operation (Operator): Function
---------------------------------------------
> Addition (+) : np.add(a,b)                          
> Subtraction (-) : np.sub(a,b)                               
> Multiply (\*) : np.multiply(a,b)                               
> Divide (/) : np.divide(a,b)                           
> Modulus (%) : np.mod(a,b)                             
> Power (\*\*) : np.power(a,b)                                 
> Reciprocal (1/a) : np.reciprocal(a)                             

## Addition

In [9]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,9,5,7])

#Using the Addition 
res1 = arr1 + 2
print(res1)

res1 = arr1 + arr2
print(res1)

#using the function
res2 = np.add(arr1, arr2)
print(res2)

[3 4 5 6 7]
[ 3  5 12  9 12]
[ 3  5 12  9 12]


## Subtraction

In [10]:
#Using the Addition 
res1 = arr1 - 2
print(res1)

res1 = arr1 - arr2
print(res1)

#using the function
res2 = np.subtract(arr1, arr2)
print(res2)

[-1  0  1  2  3]
[-1 -1 -6 -1 -2]
[-1 -1 -6 -1 -2]


## Multiply

In [11]:
#Using the Addition 
res1 = arr1 * 2
print(res1)

res1 = arr1 * arr2
print(res1)

#using the function
res2 = np.multiply(arr1, arr2)
print(res2)

[ 2  4  6  8 10]
[ 2  6 27 20 35]
[ 2  6 27 20 35]


## Divide

In [12]:
#Using the Addition 
res1 = arr1 / 2
print(res1)

res1 = arr1 / arr2
print(res1)

#using the function
res2 = np.divide(arr1, arr2)
print(res2)

[0.5 1.  1.5 2.  2.5]
[0.5        0.66666667 0.33333333 0.8        0.71428571]
[0.5        0.66666667 0.33333333 0.8        0.71428571]


## Modulus

In [13]:
#Using the Addition 
res1 = arr1 % 2
print(res1)

res1 = arr1 % arr2
print(res1)

#using the function
res2 = np.mod(arr1, arr2)
print(res2)

[1 0 1 0 1]
[1 2 3 4 5]
[1 2 3 4 5]


## Power

In [14]:
#Using the Addition 
res1 = arr1 ** 2
print(res1)

res1 = arr1 ** arr2
print(res1)

#using the function
res2 = np.power(arr1, arr2)
print(res2)

[ 1  4  9 16 25]
[    1     8 19683  1024 78125]
[    1     8 19683  1024 78125]


## Reciprocal

In [15]:
#Using the Addition 
res1 = 1/arr1
print(res1)

#using the function
res2 = np.reciprocal(arr1)
print(res2)

[1.         0.5        0.33333333 0.25       0.2       ]
[1 0 0 0 0]
