# Shape & Reshape in NumPy

# Shape

In the NumPy module, 'shape' attribute is used to determine the dimensions of an array. It provides information about the size of each dimension along with the total number of dimensions in the array. The 'shape' attribute is particularly useful for understanding the structure and size of a NumPy array.

In [1]:
import numpy as np

arr = np.array([[1,2],[5,6]])
print(arr)
print()
print(arr.shape)

print()

arr = np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print()
print(arr.shape)

[[1 2]
 [5 6]]

(2, 2)

[[1 2 3 4]
 [4 5 6 7]]

(2, 4)


## Difference between ndim & shape attribute

> 'ndim' tells the number of dimensions of the array, whereas 'shape' tells the number of elements of each dimensions.

In [2]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


# Reshape

Reshaping means change the number of dimension of an array. By reshaping we can add or remove dimensions of an array or change number of elements of each dimensions.

In [3]:
#Reshape form 1D to 2D

arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr.ndim)

print()
arr1 = arr.reshape(2,4)
print(arr1)
print(arr1.ndim)

[1 2 3 4 5 6 7 8]
1

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
#Reshape form 1D to 3D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(arr.ndim)
print(arr.shape)

print()
arr1 = arr.reshape(2,3,2)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


## Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4))
print()
print(arr.reshape(3,3))

[[1 2 3 4]
 [5 6 7 8]]



ValueError: cannot reshape array of size 8 into shape (3,3)

### What type of value 'Reshape' attributes return?

Check the returned array is a copy array or view array ->

    using base function we can know this. If it returns none then it will copy array else it a view array.

In [6]:
arr = np.array([1,2,3,4,5,6])
arr1 = arr.reshape(2,3)
print(arr1.base)

# Reshape functions returns a view array.

[1 2 3 4 5 6]


# Unknown Dimension

NumPy library allows us to have one 'unknown' dimension, means we don't have to specify an exact number for one of the dimensions in the reshape method. Pass '-1' as the value, and NUmPy will calculate the value for us.                        

It will raise an error if the number of elements are not matched.

In [7]:
arr = np.array([1,2,3,4,5,6])

arr1 = arr.reshape(2,-1)
print(arr1)
print()
print(arr1.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [8]:
arr = np.array([1,2,3,4,5,6,7])

arr1 = arr.reshape(2,-1)
print(arr1)

ValueError: cannot reshape array of size 7 into shape (2,newaxis)

# Flattening the Arrays

Flattening array means converting a multidimensional array into a 1D array.                                     

We can use reshape(-1) to do this.

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

print()
arr1 = arr.reshape(-1)
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[1 2 3 4 5 6 7 8 9]
(9,)
