# Iteration in NumPy

Iterating means going through elements one by one. As we deal with multi-dimention array in NumPy, we can do this using for loop of python.

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print()
for x in arr:
    print(x)

[1 2 3 4]

1
2
3
4


In [2]:
#By using one for loop in 2D array, it will go through all the rows

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print()
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]

[1 2 3]
[4 5 6]


In [6]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print()
for x in arr:
    for y in x:
        print(y)

[[1 2 3]
 [4 5 6]]

1
2
3
4
5
6


In [8]:
arr = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(arr)

print()
for x in arr:
    for y in x:
        for z in y:
            print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1
2
3
4
5
6
7
8


So, if we iterate on nD array it will go through (n-1)th dimensions one by one.                       
Means we need n numbers of for loops for nD array.

# Iterating Arrays using nditer()

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.

In [9]:
arr = np.array([1,2,3,4])
print(arr)
print()
for x in np.nditer(arr):
    print(x)

[1 2 3 4]

1
2
3
4


In [10]:
arr = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(arr)
print()
for x in np.nditer(arr):
    print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types

We can use 'op_dtypes' argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [17]:
arr = np.array([1,2,3,4])
print(arr)
print()
for x in np.nditer(arr, flags=['buffered'], op_dtypes = ['complex']):
    print(x)
print()
for x in np.nditer(arr, flags=['buffered'], op_dtypes = ['S']):
    print(x)

[1 2 3 4]

(1+0j)
(2+0j)
(3+0j)
(4+0j)

b'1'
b'2'
b'3'
b'4'


## Iterating With Different Step Size

We can skip elements while iterating

In [22]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print()
for x in np.nditer(arr[:, ::2]):
        print(x)

print()        

for x in np.nditer(arr[:, ::3]):
        print(x)

print()        

arr = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(arr)
print()
for x in np.nditer(arr[:, ::2]):
    print(x)

[[1 2 3]
 [4 5 6]]

1
3
4
6

1
4

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1
2
5
6


## Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [27]:
arr = np.array([1,2,3,4])
print(arr)
print()
for i,x in np.ndenumerate(arr):
    print(i,x)

[1 2 3 4]

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print()
for i,x in np.ndenumerate(arr):
    print(i,x)

[[1 2 3 4]
 [5 6 7 8]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [29]:
arr = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(arr)
print()
for i,x in np.ndenumerate(arr):
    print(i,x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
